node_id=1
node_name=primary1
conninfo='host=162.193.1.10 port=5430 user=repmgr dbname=repmgr password=REPMGR@password'
data_directory='/var/lib/postgresql/18/main'
log_level=INFO
use_replication_slots=1
promote_command='repmgr standby promote -f /etc/repmgr/18/repmgr.conf'
follow_command='repmgr standby follow -f /etc/repmgr/18/repmgr.conf'
monitoring_history=yes
